baseURL = "https://blockdailynews.online/"
languageCode = "ko-kr"
title = "ë°”ì´ë‚¸ìŠ¤"
theme = "hugo-xmag"

# í•œ í˜ì´ì§€ì— ë³´ì—¬ì¤„ ê¸°ì‚¬ ìˆ˜
[pagination]
  pagerSize = 9

enableRobotsTXT = true

# ë‹¤í¬ëª¨ë“œ ê¸°ë³¸ê°’ (light / dark)
[params]
  defaultMode = "light"
  description = "ë¸”ë¡ì²´ì¸, ê°€ìƒìì‚°, ì˜¨ì²´ì¸ ë°ì´í„°, ê·œì œÂ·ì •ì±…ê¹Œì§€ í•œ ë²ˆì— ë³´ëŠ” ë°”ì´ë‚¸ìŠ¤ ë¸”ë¡ì²´ì¸ ì¹¼ëŸ¼"

  # ğŸ”¹ Newsroom ë©”ì¸ ì„¹ì…˜/ì•„ì¹´ì´ë¸Œ ì„¤ì •
  blogDir = "news"         # View Archive ë²„íŠ¼ â†’ /news ë¡œ ì´ë™
  mainSections = ["news"]  # ë©”ì¸ì— ë‚˜ì˜¤ëŠ” ê¸€ íƒ€ì… = content/news/*
  contact_email = "bearlavender@naver.com"
[markup.goldmark.renderer]
  unsafe = true          # raw HTML ë Œë” í—ˆìš©

ignoreLogs = ['warning-goldmark-raw-html']